name: Continious Integration
on: push

jobs:
    psalm:
        name: Psalm
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: shivammathur/setup-php@master
              with:
                  php-version: '8.1'
            - name: Install dependencies
              run: composer update
            - name: Run Psalm
              run: vendor/bin/psalm

    phpunit:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '8.1', '8.2', '8.3' ]
                prefer-lowest: [ '', '--prefer-lowest' ]
        steps:
            - uses: actions/checkout@master
            - uses: shivammathur/setup-php@master
              with:
                  php-version: ${{ matrix.php }}
            - name: Install dependencies
              run: composer update -n --prefer-dist  ${{ matrix.prefer-lowest }}
            - name: Run PHPUnit unit tests
              run: vendor/bin/phpunit

    coding_standards:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: shivammathur/setup-php@master
              with:
                  php-version: '8.1'
            - name: Install dependencies
              run: composer update
            - name: Run PHP-CS-Fixer
              run: vendor/bin/php-cs-fixer fix --dry-run -v

    check-licenses:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@master
            -   uses: shivammathur/setup-php@master
                with:
                    php-version: '8.1'
            -   name: Install dependencies
                run: composer update
            -   name: Run License Checker
                run: bin/license-checker check --quiet
